service: BE-SERVICE

useDotenv: true

plugins:
    - serverless-offline

provider:
    name: aws
    runtime: nodejs12.x
    environment:
    MONGODB_URI: ${env:MONGODB_URI}
    AUTH_REDIRECT_URI: ${env:AUTH_REDIRECT_URI}
functions:
    main:
        handler: dist/serverless.handler
        events:
            - http:
                  method: ANY
                  path: /
            - http:
                  method: ANY
                  path: '{proxy+}'
